import globals from 'globals'
import pluginJs from '@eslint/js'
import tseslint from 'typescript-eslint'
import eslintPluginPrettierRecommended from 'eslint-plugin-prettier/recommended'

/** @type {import('eslint').Linter.Config[]} */
export default [
  eslintPluginPrettierRecommended,
  {
    files: ['**/*.{js,mjs,cjs,ts}']
  },
  {
    ignores: ['dist/*']
  },
  {
    languageOptions: {
      globals: globals.browser
    }
  },
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      'comma-dangle': 'off',
      'no-restricted-globals': [
        // allow some functions of `window`:
        // 'document',
        // 'setTimeout',
        // 'clearTimeout',
        // 'setInterval',
        // 'clearInterval',
        // 'requestIdleCallback',
        // 'cancelIdleCallback',
        // 'requestAnimationFrame',
        // 'cancelAnimationFrame',
        // do not allow all other keys of the global `window` object:
        'error',
        'close',
        'stop',
        'focus',
        'blur',
        'open',
        'alert',
        'confirm',
        'prompt',
        'print',
        'postMessage',
        'captureEvents',
        'releaseEvents',
        'getSelection',
        'getComputedStyle',
        'matchMedia',
        'moveTo',
        'moveBy',
        'resizeTo',
        'resizeBy',
        'scroll',
        'scrollTo',
        'scrollBy',
        'getDefaultComputedStyle',
        'scrollByLines',
        'scrollByPages',
        'updateCommands',
        'find',
        'dump',
        'setResizable',
        'reportError',
        'btoa',
        'atob',
        'queueMicrotask',
        'createImageBitmap',
        'structuredClone',
        'fetch',
        'self',
        'name',
        'history',
        'customElements',
        'locationbar',
        'menubar',
        'personalbar',
        'scrollbars',
        'statusbar',
        'toolbar',
        'status',
        'closed',
        'event',
        'frames',
        'length',
        'opener',
        'parent',
        'frameElement',
        'navigator',
        'clientInformation',
        'external',
        'screen',
        'innerWidth',
        'innerHeight',
        'scrollX',
        'pageXOffset',
        'scrollY',
        'pageYOffset',
        'screenLeft',
        'screenTop',
        'screenX',
        'screenY',
        'outerWidth',
        'outerHeight',
        'performance',
        'mozInnerScreenX',
        'mozInnerScreenY',
        'devicePixelRatio',
        'scrollMaxX',
        'scrollMaxY',
        'fullScreen',
        'ondevicemotion',
        'ondeviceorientation',
        'ondeviceorientationabsolute',
        'InstallTrigger',
        'visualViewport',
        'crypto',
        'onabort',
        'onblur',
        'onfocus',
        'oncancel',
        'onauxclick',
        'onbeforeinput',
        'onbeforetoggle',
        'oncanplay',
        'oncanplaythrough',
        'onchange',
        'onclick',
        'onclose',
        'oncontentvisibilityautostatechange',
        'oncontextlost',
        'oncontextmenu',
        'oncontextrestored',
        'oncopy',
        'oncuechange',
        'oncut',
        'ondblclick',
        'ondrag',
        'ondragend',
        'ondragenter',
        'ondragexit',
        'ondragleave',
        'ondragover',
        'ondragstart',
        'ondrop',
        'ondurationchange',
        'onemptied',
        'onended',
        'onformdata',
        'oninput',
        'oninvalid',
        'onkeydown',
        'onkeypress',
        'onkeyup',
        'onload',
        'onloadeddata',
        'onloadedmetadata',
        'onloadstart',
        'onmousedown',
        'onmouseenter',
        'onmouseleave',
        'onmousemove',
        'onmouseout',
        'onmouseover',
        'onmouseup',
        'onwheel',
        'onpaste',
        'onpause',
        'onplay',
        'onplaying',
        'onprogress',
        'onratechange',
        'onreset',
        'onresize',
        'onscroll',
        'onscrollend',
        'onsecuritypolicyviolation',
        'onseeked',
        'onseeking',
        'onselect',
        'onslotchange',
        'onstalled',
        'onsubmit',
        'onsuspend',
        'ontimeupdate',
        'onvolumechange',
        'onwaiting',
        'onselectstart',
        'onselectionchange',
        'ontoggle',
        'onpointercancel',
        'onpointerdown',
        'onpointerup',
        'onpointermove',
        'onpointerout',
        'onpointerover',
        'onpointerenter',
        'onpointerleave',
        'ongotpointercapture',
        'onlostpointercapture',
        'onmozfullscreenchange',
        'onmozfullscreenerror',
        'onanimationcancel',
        'onanimationend',
        'onanimationiteration',
        'onanimationstart',
        'ontransitioncancel',
        'ontransitionend',
        'ontransitionrun',
        'ontransitionstart',
        'onwebkitanimationend',
        'onwebkitanimationiteration',
        'onwebkitanimationstart',
        'onwebkittransitionend',
        'onerror',
        'speechSynthesis',
        'onafterprint',
        'onbeforeprint',
        'onbeforeunload',
        'onhashchange',
        'onlanguagechange',
        'onmessage',
        'onmessageerror',
        'onoffline',
        'ononline',
        'onpagehide',
        'onpageshow',
        'onpopstate',
        'onrejectionhandled',
        'onstorage',
        'onunhandledrejection',
        'onunload',
        'ongamepadconnected',
        'ongamepaddisconnected',
        'localStorage',
        'origin',
        'crossOriginIsolated',
        'isSecureContext',
        'indexedDB',
        'caches',
        'sessionStorage',
        'location',
        'top',
        'RPMSendAsyncMessage',
        'RPMAddMessageListener',
        'ContentSearchUIController',
        'ContentSearchHandoffUIController',
        'React',
        'ReactDOM',
        'PropTypes',
        'ReactTransitionGroup',
        'Redux',
        'ReactRedux',
        'NewtabRenderUtils',
        'reactiveElementVersions',
        'litHtmlVersions',
        'litElementVersions'
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          args: 'all',
          argsIgnorePattern: '^_',
          caughtErrors: 'all',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          ignoreRestSiblings: true
        }
        // source: https://github.com/johnnyreilly/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-unused-vars.md
      ]
    }
  }
]
